-- Runs on every application start (spring.sql.init.mode=always),
-- so every statement must be safe to run again on an existing database.
CREATE TABLE IF NOT EXISTS patients (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(254) NOT NULL UNIQUE,
    -- Wide enough for a password hash, not just the raw password (max 64 chars).
    password     VARCHAR(64) NOT NULL,
    id_card_no   VARCHAR(9)   NOT NULL,
    first_name   VARCHAR(50)  NOT NULL,
    last_name    VARCHAR(50)  NOT NULL,
    phone_number VARCHAR(9)   NOT NULL,
    birthday     DATE
);
